// @ts-nocheck
/**
 * 11-mapped-template-keys — THE JAVASCRIPT VERSION (unchecked)
 * ---------------------------------------------------------------------------
 * A "getters" object generated by convention: for every field on `Order`,
 * there should be a `get<FieldName>` accessor. Nothing in JavaScript
 * generates or checks these keys — they are simply typed out by hand, and a
 * typo in one is exactly as invisible as every other typo in this project,
 * just wearing a slightly longer name.
 *
 * DOMAIN: a hand-rolled accessor object for an order-detail view.
 */

import { section, js, note, detonate, runtimeSays, table, blank } from "../99-runner/trace.js";

function loadOrder() {
  return { id: "o-9001", totalCents: 3300, customerEmail: "hedy@example.com" };
}

export function runBroken() {
  const order = loadOrder();

  const getters = {
    getId: () => order.id,
    // Typo: should be 'getTotalCents' (matching the field 'totalCents').
    getTotalCent: () => order.totalCents,
    getCustomerEmail: () => order.customerEmail,
  };

  section("Calling the generated-by-convention accessors");

  js("getters.getId()");
  detonate("getters.getId()", () => getters.getId());

  blank();
  js("getters.getTotalCents()  — the name a caller would naturally guess");
  detonate("getters.getTotalCents()", () => getters.getTotalCents());
  runtimeSays(
    "TypeError: getters.getTotalCents is not a function",
    "The accessor exists — as 'getTotalCent', missing the trailing 's' — so " +
      "calling the name every OTHER field's convention would predict throws.",
  );

  blank();
  section("The convention, and where it silently broke");
  table(
    ["field", "expected accessor", "actually generated"],
    [
      ["id", "getId", "getId (correct)"],
      ["totalCents", "getTotalCents", "getTotalCent (typo)"],
      ["customerEmail", "getCustomerEmail", "getCustomerEmail (correct)"],
    ],
  );
  note(
    "One typo in a hand-typed key breaks the convention for exactly one " +
      "field, and nothing about defining the object flagged it.",
  );
}
